export const authConstants = {
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  VALIDATE_REQUEST: 'VALIDATE_REQUEST',
  VALIDATE_SUCCESS: 'VALIDATE_SUCCESS',
  VALIDATE_FAILURE: 'VALIDATE_FAILURE',

  LOGOUT: 'LOGOUT',
};

export const articleConstants = {
  ADD_ARTICLE: 'ADD_ARTICLE',
  FETCH_ARTICLES: 'FETCH_ARTICLES'
};
